
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - cloudflare_network
    env_file:
      - ../../.env      # Global env - chứa CLOUDFLARE_TOKEN
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    profiles:
      - all
      - cloudflared
